#!/bin/bash
rm ./nohup.out
nohup nice -n 10 ./ES_RNN_Daily 0 &
nohup nice -n 10 ./ES_RNN_Daily 10 &
nohup nice -n 10 ./ES_RNN_Daily 20 &
nohup nice -n 10 ./ES_RNN_Daily 30 &
nohup nice -n 10 ./ES_RNN_Daily 40 &
nohup nice -n 10 ./ES_RNN_Daily 50 &
nohup nice -n 10 ./ES_RNN_Daily 60 &
nohup nice -n 10 ./ES_RNN_Daily 70 &
